### ISSUE TITLE
Block comments and regex treatment

### ISSUE THREAD

**Issue by j-k** [Edditoria/coffeescript_npp_zenburn#2]
Between block comments, like this
### 

if true then false
### 

the items are not colored as comment but as key words.
Similary, the characters beween a regex are not colored like in strings, example:
/if true then false/ will highlight the words in the regex as key words.

**Comment by Edditoria** [comment]
Hi, I'm back from 2013.

This bug occurs because of UDL version. Problem fixed. Thanks!
